window.dict = {
  chat: "Chat",
  support: "Support",
  language: "Language:",
  login: "Login",
  submit: "Submit",
  register: "Registration",
  password: "Forgot the password?",
  remain: "Remain in the system",
  usr_det: "User details",
  pers_inf: "Personal info",
  confim: "Comfirmation",
  usrname: "Username",
  pass: "Password",
  pass_conf: "Confirm password:",
  fields: "All the fields, marked by (*) are required.",
  next: "Next",
  my_bets: "My bets",
  cash_out: "Cash out",
  cash_out_main: "Cash out",
  live: "Live",
  betslip: "Bet slip",
  multiodds: "Multiply Odds",
  unsettled: "Unsettled",
  settled: "Settled",
  all: "All",
  edit_bet: "Edit bet",
  full_time: "Fulltime result",
  stake: "To Stake",
  return: "Return",
  usr__balmanage: "Balance management",
  usr__persinfo: "Personal information",
  usr__transahist: "Transaction history",
  usr__accesslog: "Access log",
  usr__accountmanagement: "Account management",
  usr__casier: "Casier",
  usr__deposit: "Deposit",
  usr__withdraw: "Withdraw",
  usr__accountmanagement: "Account Management",
  usr__title: "Title",
  usr__money: "Money",
  usr__moneytransfer: "Money Transfer",
  usr__mainbalance: "Main balance",
  usr__transfmoneyfrom: "Transfer money from",
  usr__transfmoneyto: "Transfer money to",
  usr__pocker3d: "Pocker 3D",
  usr__amount: "Amount",
  usr__transfer: "Transfer",
  usr__provider: "Provider",
  usr__minamount: "Min.amount",
  usr__maxamount: "Max.amount",
  usr__instruction: "Instruction",
  usr__usrinfo: "User information",
  usr__security: "Security",
  usr__notification: "Notification",
  usr__accinfo: "Account info",
  usr__usrname: "User name:",
  usr__commulng: "Communication language:",
  usr__userid: "User ID:",
  usr__status: "Status:",
  usr__email: "Email:",
  usr__mobile: "Mobile:",
  usr__contdetails: "Contact details",
  usr__persdetails: "Personal details",
  usr__name: "Name:",
  usr__lastname: "Last name:",
  usr__gender: "Gender:",
  usr__bday: "Date of birth:",
  usr_chngpw: "Change password",
  usr_currgpw: "Current password:",
  usr_newpw: "New Password:",
  usr_confpw: "Confirm Password:",
  usr_hsecur: "High Security",
  usr_byactiv: "By activating High Security your adjarabet.com account is safe and secure from unauthorized access. Access to your account and personal information is only possible by security code.",
  usr_yes: "Yes",
  usr_no: "No",
  usr_save: "Save",
  usr_phonecode: "Telephone code",
  usr_reset: "Reset",
  usr_phonecode_descr: "Telephone code is a randomly generated 8-digit combination which user uses for resolving personal account issue with adjarabet.com hotline",
  usr__range: "Range:",
  usr__notransaction: "No Transaction Found",
  usr__transacfilter_all: "All",
}