window.dict = {
  chat: "Чат",
  support: "Поддержка",
  language: "Язык:",
  login: "Войти",
  submit: "Подтвердить",
  register: "Регистрация",
  password: "Забыли пароль?",
  remain: "Оставаться в системе",
  usr_det: "Аккаунт",
  pers_inf: "Подробная информация",
  confim: "Подтверждение",
  usrname: "Имя пользователя:",
  pass: "Пароль:",
  pass_conf: "Подтвердите пароль:",
  fields: "Все поля, помеченные * обязательны.",
  next: "Дальше",
  my_bets: "Мои ставки",
  cash_out: "Вывести",
  live: "В игре",
  betslip: "Купон ставки",
  multiodds: "Умножить Шансы",
  unsettled: "Несыгранные",
  settled: "Сыгранные",
  all: "Все",
  cash_out_main: "Вывести",
  edit_bet: "Редактировать",
  full_time: "Результат",
  stake: "Поставить",
  return: "Вернуть",
  usr__balmanage: "Управление балансом",
  usr__persinfo: "Личная информация",
  usr__transahist: "История транзакций",
  usr__accesslog: "История доступа",
  usr__accountmanagement: "Управление аккаунтом",
  usr__withdraw: "Вывести",
  usr__casier: "Кассир",
  usr__deposit: "Депозит",
  usr__transahist: "История переводов",
  usr__accountmanagement: "Управление Аккаунтом",
  usr__title: "Название",
  usr__money: "Деньги",
  usr__moneytransfer: "Денежный перевод",
  usr__mainbalance: "Основной счёт",
  usr__transfmoneyfrom: "Перевести деньги из",
  usr__transfmoneyto: "Перевести деньги в",
  usr__pocker3d: "Покер 3D",
  usr__amount: "Количество",
  usr__transfer: "Перевести",
  usr__provider: "Поставщик",
  usr__minamount: "Мин. кол-во",
  usr__maxamount: "Макс. кол-во",
  usr__instruction: "Инструкции",
  usr__usrinfo: "Информация пользователя",
  usr__security: "Безопасность",
  usr__notification: "Уведомления",
  usr__accinfo: "Инфо. о аккаунте",
  usr__usrname: "Имя пользователя:",
  usr__commulng: "Язык:",
  usr__userid: "Идентификатор пользователя:",
  usr__status: "Статус:",
  usr__email: "Эл. почта:",
  usr__mobile: "Телефон:",
  usr__contdetails: "Контактные данные",
  usr__persdetails: "Персональные данные",
  usr__name: "Имя:",
  usr__lastname: "Фамилия:",
  usr__gender: "Пол:",
  usr__bday: "Дата рождения:",
  usr_chngpw: "Изменить пароль",
  usr_currgpw: "Текущий пароль:",
  usr_newpw: "Новый пароль:",
  usr_confpw: "Подтверждение пароля:",
  usr_hsecur: "Пов. безопасность",
  usr_byactiv: "Активируя повышенную безопасность ваша учетная запись безопасна и защищена от неавторизованного доступа. Доступ к вашему аккаунту и персональной информации возможен только по коду безопасности.",
  usr_yes: "Да",
  usr_no: "Нет",
  usr_save: "Сохранить",
  usr_phonecode: "Код со смартфона",
  usr_reset: "Восстановить",
  usr_phonecode_descr: "Код со смартфона это случайно сгенерированная 8-числовая комбинация которую пользователь использует для решения проблемы с личным аккаунтом на горячей линии",
  usr__range: "Диапазон:",
  usr__notransaction: "Не найдено переводов",
  usr__transacfilter_all: "Все",
}