window.dict = {
  chat: "Чат",
  support: "Поддержка",
  language: "Язык:",
  login: "Войти",
  submit: "Подтвердить",
  register: "Регистрация",
  password: "Забыли пароль?",
  remain: "Оставаться в системе",
  usr_det: "Аккаунт",
  pers_inf: "Подробная информация",
  confim: "Подтверждение",
  usrname: "Имя пользователя:",
  pass: "Пароль:",
  pass_conf: "Подтвердите пароль:",
  fields: "Все поля, помеченные * обязательны.",
  next: "Дальше",
  my_bets: "Мои ставки",
  cash_out: "Вывести",
  live: "В игре",
  betslip: "Купон ставки",
  multiodds: "Умножить Шансы",
  unsettled: "Несыгранные",
  settled: "Сыгранные",
  all: "Все",
  cash_out_main: "Вывести",
  edit_bet: "Редактировать",
  full_time: "Результат",
  stake: "Поставить",
  return: "Вернуть",
}